import assert from 'node:assert/strict';import {writeFileSync} from 'node:fs';const {chromium}=await import(process.env.PLAYWRIGHT_MODULE ?? 'playwright');
const b=await chromium.launch();const results=[];const url=process.env.STUDIO_HOST_URL;assert.ok(url,'STUDIO_HOST_URL is required');
try {
const c=await b.newContext();const p=await c.newPage();const requests=[];p.on('request',r=>requests.push(r.url()));await p.goto(url+'/#scenario=tasks.list');await p.getByText('Ready',{exact:true}).first().waitFor();assert.equal(requests.some(x=>/\/design(?:-tokens)?\.tsx/.test(x)),false);
await p.keyboard.press('5');const tabs=p.getByRole('group',{name:'Design tab',exact:true});await tabs.waitFor();await p.getByLabel('Density',{exact:true}).waitFor();results.push({check:'cold keyboard Design opening loads controls',pass:true});
await p.getByLabel('Density',{exact:true}).fill('1.13');await p.getByLabel('Density',{exact:true}).press('Tab');const editedURL=p.url();assert.ok(editedURL.includes('design='));
let release;const held=new Promise(r=>release=r);await p.route('**/src/components/studio/design-tokens.tsx*',async route=>{await held;await route.continue()});const tokens=tabs.getByRole('button',{name:'Tokens',exact:true});await tokens.focus();await p.keyboard.press('Space');await p.getByText('Loading token controls',{exact:true}).waitFor();assert.equal(await tokens.evaluate(e=>e===document.activeElement),true);release();await p.getByPlaceholder('Name or value',{exact:true}).waitFor();assert.equal(await tokens.evaluate(e=>e===document.activeElement),true);await tabs.getByRole('button',{name:'Adjust',exact:true}).click();await p.getByLabel('Density',{exact:true}).waitFor();assert.equal(await p.getByLabel('Density',{exact:true}).inputValue(),'1.13');results.push({check:'cold Tokens selected tab retains keyboard focus through delayed chunk and working draft survives tab return',pass:true});
await p.keyboard.press('Escape');await tabs.getByRole('button',{name:'Adjust',exact:true}).focus();await p.keyboard.press('4');await p.getByRole('button',{name:'Play',exact:true}).waitFor();results.push({check:'Present opens after lazy Design without clearing draft link',pass:true});await c.close();
const stale=await b.newPage();await stale.goto(url+'/#view=design&scenario=tasks.list&design=iconStyle:unavailable');await stale.getByLabel('Density',{exact:true}).waitFor();await stale.getByRole('status').filter({hasText:'unavailable saved appearance'}).waitFor();assert.ok(stale.url().includes('view=design'));results.push({check:'cold Design deep link and stale appearance recovery remain honest',pass:true});await stale.close();
const fail=await b.newPage();await fail.route('**/src/components/studio/design-tokens.tsx*',r=>r.abort());await fail.goto(url+'/#view=design&scenario=tasks.list');await fail.getByLabel('Density',{exact:true}).waitFor();await fail.getByLabel('Density',{exact:true}).fill('1.12');await fail.getByLabel('Density',{exact:true}).press('Tab');await fail.getByRole('group',{name:'Design tab',exact:true}).getByRole('button',{name:'Tokens',exact:true}).click();await fail.getByRole('alert').filter({hasText:'could not load'}).first().waitFor();await fail.getByRole('group',{name:'Design tab',exact:true}).getByRole('button',{name:'Adjust',exact:true}).click();await fail.getByLabel('Density',{exact:true}).waitFor();assert.equal(await fail.getByLabel('Density',{exact:true}).inputValue(),'1.12');results.push({check:'rejected lazy token chunk stays local; working Adjust draft survives and remains reachable',pass:true});await fail.close();
}finally{await b.close();writeFileSync(process.env.STUDIO_LAZY_EVIDENCE ?? 'lazy-boundaries.json',JSON.stringify(results,null,2)+'\n')}
console.log(JSON.stringify(results));
