import {captureResources} from '../capture.mjs';
const {chromium,webkit}=await import(process.env.PLAYWRIGHT_MODULE??'playwright');
import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
const outputRoot=process.env.DIAGNOSTIC_OUTPUT??'./diagnostic-evidence';mkdirSync(outputRoot,{recursive:true});
const red=process.env.DIAGNOSTIC_MODE==='red',message=readFileSync(new URL('./message.txt',import.meta.url),'utf8').trimEnd(),results=[],resourceRuns=[];
for(const engine of ['chromium','webkit']){const browser=await(engine==='webkit'?webkit:chromium).launch(engine==='webkit'?{executablePath:process.env.PLAYWRIGHT_WEBKIT_EXECUTABLE}:{});
 for(const [host,root]of[['vite',process.env.STUDIO_VITE_URL??'http://127.0.0.1:4221'],['next',process.env.STUDIO_NEXT_URL??'http://127.0.0.1:4222']])for(const width of[1440,768,390]){
  const context=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce'}),page=await context.newPage(),errors=[],posts=[];const finishResources=captureResources(page,root);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()==='POST')posts.push(r.url())});await page.goto(`${root}/#view=design&scenario=tasks.list`);await page.waitForFunction(()=>document.querySelector('iframe.opacity-100')?.contentWindow.__fixtureCompiled?.asset==='loaded');await page.evaluate(()=>document.fonts.ready);if(width===390)await page.getByRole('button',{name:'Panel',exact:true}).click();await page.getByRole('combobox',{name:'Registered asset',exact:true}).waitFor();const ready=await page.locator('[data-design-status]').evaluateAll(es=>es.map(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height,x:e.getBoundingClientRect().x,text:e.textContent})));await page.locator('iframe.opacity-100').first().evaluate(e=>{e.contentWindow.__diagnosticDocument=e.contentDocument;e.contentWindow.__diagnosticBody=e.contentDocument.body});const asset=page.getByRole('combobox',{name:'Registered asset',exact:true});await asset.scrollIntoViewIfNeeded();await asset.click();await page.getByRole('option',{name:'Missing',exact:true}).click();await page.locator('[data-design-status] p[role=alert]').first().waitFor();
  const diagnostic=await page.locator('[data-design-status]').evaluateAll((es,msg)=>es.map(e=>({width:e.clientWidth,scrollWidth:e.scrollWidth,rect:e.getBoundingClientRect().toJSON(),text:e.textContent,paragraphs:[...e.querySelectorAll('p[role=alert]')].map(p=>{const range=document.createRange();range.selectNodeContents(p);const box=p.getBoundingClientRect(),rects=[...range.getClientRects()].map(r=>({left:r.left,right:r.right,width:r.width}));return{text:p.textContent,full:p.textContent.includes(msg),width:p.clientWidth,scrollWidth:p.scrollWidth,wrap:getComputedStyle(p).overflowWrap,rects,rangeInside:rects.every(r=>r.left>=box.left-1&&r.right<=box.right+1)}}),controls:[...e.querySelectorAll('button')].map(b=>{const r=b.getBoundingClientRect(),p=e.getBoundingClientRect();return{text:b.textContent,inside:r.left>=p.left-1&&r.right<=p.right+1}})})),message);
  const frame=await page.locator('iframe.opacity-100').first().evaluate(e=>({asset:e.contentWindow.__fixtureCompiled?.asset,scale:e.contentWindow.__fixtureCompiled?.scale,sameDocument:e.contentWindow.__diagnosticDocument===e.contentDocument,sameBody:e.contentWindow.__diagnosticBody===e.contentDocument.body}));if(frame.asset!=='loaded'||!frame.sameDocument||!frame.sameBody)throw Error('Last valid changed');if(!red&&diagnostic.some(s=>s.scrollWidth>s.width+1||s.paragraphs.some(p=>!p.full||!p.rangeInside||p.scrollWidth>p.width+1)||s.controls.some(c=>!c.inside)))throw Error('Diagnostic overflow/clipping');await page.screenshot({path:`${outputRoot}/${red?'red':'green'}-${engine}-${host}-${width}.png`});if(width===390)await page.keyboard.press('Escape');await page.getByRole('button',{name:'Directions',exact:true}).click();const saveBlocked=await page.getByRole('button',{name:'Save direction',exact:true}).isDisabled();if(!saveBlocked||posts.length||errors.length)throw Error('Failure became saveable or wrote/errored');results.push({engine,host,width,pass:true,red,ready,diagnostic,frame,saveBlocked,errors,posts});writeFileSync(`${outputRoot}/${red?'red':'green'}-progress.json`,JSON.stringify(results,null,2));resourceRuns.push({engine,host,width,resources:await finishResources()});writeFileSync(`${outputRoot}/${red?'red':'green'}-resources.json`,JSON.stringify(resourceRuns,null,2));await context.close();
 }await browser.close();}
writeFileSync(`${outputRoot}/${red?'red':'green'}.json`,JSON.stringify(results,null,2));
