import {captureResources} from './capture.mjs';
const {chromium,webkit} = await import(process.env.PLAYWRIGHT_MODULE ?? 'playwright');
import {mkdirSync,writeFileSync} from 'node:fs';
const outputRoot=process.env.POPOVER_OUTPUT??'./popover-focus-evidence';
mkdirSync(outputRoot,{recursive:true});
const results=[],resourceRuns=[];
for(const engine of ['chromium','webkit']){const browser=await(engine==='webkit'?webkit:chromium).launch(engine==='webkit'?{executablePath:process.env.PLAYWRIGHT_WEBKIT_EXECUTABLE}:{});
 for(const [host,root] of [['vite',process.env.STUDIO_VITE_URL??'http://127.0.0.1:4221'],['next',process.env.STUDIO_NEXT_URL??'http://127.0.0.1:4222']]) for(const width of [1440,390]) for(const mode of ['controlled-choice','uncontrolled']){
  const context=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce'}),page=await context.newPage(),errors=[],posts=[];const finishResources=captureResources(page,root);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()==='POST')posts.push(r.url())});
  await page.goto(`${root}/${mode==='uncontrolled'?'?uncontrolled':''}#view=design&scenario=tasks.list`);await page.getByRole('button',{name:'Directions',exact:true}).waitFor();if(width===390)await page.getByRole('button',{name:'Panel',exact:true}).click();const opener=page.getByRole('button',{name:'Palette picker',exact:true});await opener.click();const popup=page.getByRole('dialog',{name:'Registered palette',exact:true});await popup.waitFor();await page.screenshot({path:`${outputRoot}/${engine}-${host}-${width}-${mode}.png`});
  let lastTab=true,firstShiftTab=true;
  if(mode==='controlled-choice'){await popup.getByRole('combobox',{name:'Palette',exact:true}).click();await page.getByRole('option',{name:'Green',exact:true}).click();await popup.waitFor({state:'hidden'});await page.waitForFunction(()=>document.activeElement?.textContent==='Palette picker');await page.waitForFunction(()=>document.querySelector('iframe.opacity-100')?.contentWindow.__fixtureCompiled?.light==='green');}
  else{const first=popup.getByRole('combobox',{name:'Palette',exact:true}),last=popup.getByRole('button',{name:'Close picker',exact:true});await last.focus();await page.keyboard.press('Tab');await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));lastTab=await popup.evaluate(e=>e.contains(document.activeElement));await first.focus();await page.keyboard.press('Shift+Tab');await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));firstShiftTab=await popup.evaluate(e=>e.contains(document.activeElement));if(!lastTab||!firstShiftTab)throw Error('Uncontrolled boundary escaped');await last.click();await popup.waitFor({state:'hidden'});await page.waitForFunction(()=>document.activeElement?.textContent==='Palette picker');await opener.click();await popup.waitFor();await page.keyboard.press('Escape');await popup.waitFor({state:'hidden'});await page.waitForFunction(()=>document.activeElement?.textContent==='Palette picker');}
  const sheetSurvived=width!==390||await opener.isVisible();if(!sheetSurvived||errors.length||posts.length)throw Error('Mode errors/writes/sheet dismissal');results.push({engine,host,width,mode,pass:true,lastTab,firstShiftTab,openerFocused:true,sheetSurvived,errors,posts});writeFileSync(`${outputRoot}/modes-progress.json`,JSON.stringify(results,null,2));resourceRuns.push({engine,host,width,mode,resources:await finishResources()});writeFileSync(`${outputRoot}/modes-resources.json`,JSON.stringify(resourceRuns,null,2));await context.close();
 }await browser.close();}
writeFileSync(`${outputRoot}/modes.json`,JSON.stringify(results,null,2));
