import {mkdirSync} from 'node:fs';
const out=process.env.EVIDENCE_OUT ?? new URL('.',import.meta.url).pathname;mkdirSync(out,{recursive:true});
const {chromium,webkit}=await import(process.env.PLAYWRIGHT_MODULE ?? 'playwright');
import {writeFileSync,readFileSync} from 'node:fs';
const red=process.env.INSPECTOR_MODE==='red',data=JSON.parse(readFileSync(new URL('./fixture-data.json',import.meta.url))),results=[];
for(const engine of ['chromium','webkit']){const browser=await(engine==='webkit'?webkit:chromium).launch(engine==='webkit'?(process.env.WEBKIT_EXECUTABLE ? {executablePath:process.env.WEBKIT_EXECUTABLE} : {}):{});
 for(const [host,port] of [['vite',process.env.VITE_ORIGIN ?? 'http://127.0.0.1:4225'],['next',process.env.NEXT_ORIGIN ?? 'http://127.0.0.1:4226']])for(const width of[1440,768,390])for(const mode of['short','long']){
  const context=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce'}),page=await context.newPage(),errors=[],posts=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()==='POST')posts.push(r.url())});await page.goto(`${port}/?provenance=${mode}#view=design&scenario=tasks.list&tab=tokens`);await page.getByRole('button',{name:'Source',exact:true}).first().waitFor();await page.evaluate(()=>document.fonts.ready);const buttons=await page.getByRole('button',{name:'Source',exact:true}).elementHandles(),roots=[];for(const b of buttons)roots.push(await b.evaluateHandle(e=>e.closest('[data-kit]')));
  for(const b of await page.getByRole('button',{name:'Compiled',exact:true}).elementHandles())await b.click();
  const compiled=[];for(const root of roots)compiled.push(await root.evaluate(e=>({width:e.clientWidth,scrollWidth:e.scrollWidth,tokens:[...e.querySelectorAll('dt,dd')].map(x=>({text:x.textContent,width:x.getBoundingClientRect().width,height:x.getBoundingClientRect().height}))})));
  for(const b of await page.getByRole('button',{name:'Source',exact:true}).elementHandles())await b.click();await page.getByText('Source lock:',{exact:false}).first().waitFor();
  const geometry=[];for(const root of roots)geometry.push(await root.evaluate(e=>{const b=e.getBoundingClientRect();return{width:e.clientWidth,scrollWidth:e.scrollWidth,height:e.clientHeight,bounds:b.toJSON(),overflow:getComputedStyle(e).overflow,paragraphs:[...e.querySelectorAll('p')].filter(p=>p.textContent.startsWith('Source lock:')||p.textContent.startsWith('Synthetic diagnostic:')||p.textContent.startsWith('Fingerprint')).map(p=>{const r=document.createRange();r.selectNodeContents(p);const box=p.getBoundingClientRect(),rects=[...r.getClientRects()].map(r=>({left:r.left,right:r.right,width:r.width}));return{text:p.textContent,width:p.clientWidth,scrollWidth:p.scrollWidth,height:p.clientHeight,wrap:getComputedStyle(p).overflowWrap,wordBreak:getComputedStyle(p).wordBreak,rangeInside:rects.every(r=>r.left>=box.left-1&&r.right<=box.right+1&&r.left>=b.left-1&&r.right<=b.right+1),rects}}),controls:[...e.querySelectorAll('button')].map(x=>{const r=x.getBoundingClientRect();return{text:x.textContent,inside:r.left>=b.left-1&&r.right<=b.right+1}}),preCount:e.querySelectorAll('pre').length}}));
  for(const g of geometry){const locks=g.paragraphs.filter(p=>p.text.startsWith('Source lock:')),diagnostics=g.paragraphs.filter(p=>p.text.startsWith('Synthetic diagnostic:'));if(!locks.length||locks.length!==diagnostics.length||locks.some(p=>p.text!=='Source lock: '+(mode==='long'?data.sourceLockId:'fixture-source/1'))||diagnostics.some(p=>p.text!=='Synthetic diagnostic: '+(mode==='long'?data.diagnostic:'Source verified.')))throw Error('Provenance text changed')}
  if(!red&&geometry.some(g=>g.scrollWidth>g.width+1||g.paragraphs.some(p=>p.scrollWidth>p.width+1||!p.rangeInside)||g.controls.some(c=>!c.inside)))throw Error('Inspector overflow');await page.screenshot({path:`${out}/${red?'red':'green'}-${engine}-${host}-${width}-${mode}.png`});if(errors.length||posts.length)throw Error('Read-only inspector errored/wrote');results.push({engine,host,width,mode,red,pass:true,compiled,geometry,errors,posts});writeFileSync(`${out}/${red?'red':'green'}-progress.json`,JSON.stringify(results,null,2));await context.close();
 }await browser.close();}
writeFileSync(`${out}/${red?'red':'green'}.json`,JSON.stringify(results,null,2));
