/*
 * Stress adapter: 1,000 scenarios in 12 areas, 1,000 tokens in 14 families, and a
 * 40-step walkthrough with deliberately broken steps. It exists to measure the
 * shell (npm run acceptance) and is never shown unless VITE_STUDIO_ADAPTER=synthetic
 * is set at build time (vite.config.ts points "@/adapter" here). Delete it with the example when a product adapter is in place.
 */
import { exampleAdapter } from "@/adapters/example"
import type { Scenario, Step, StudioAdapter, Token } from "@/studio/types"

const fixture = { id: "synthetic", version: "1", provenance: "Generated by the starter for stress checks" }
const AREAS = ["Onboarding", "Tasks", "Projects", "Calendar", "Inbox", "Search", "Reports", "Billing", "Settings", "Admin", "Integrations", "Help"]
const areas = AREAS.map((label) => ({ id: label.toLowerCase(), label }))

// Ids start with "syn." so the example preview can render any of them as its task list.
const scenarios: Scenario[] = Array.from({ length: 1000 }, (_, i) => {
  const area = areas[i % areas.length]
  const n = Math.floor(i / areas.length) + 1
  return {
    id: `syn.${area.id}.${n}`,
    label: `${area.label} state ${n}`,
    area: area.id,
    surface: `${area.label} surface ${Math.ceil(n / 4)}`,
    description: `Synthetic scenario ${i + 1} of 1,000.`,
    fixture,
    source: "synthetic",
    clock: "Fixed",
    status: i % 97 === 0 ? "stale" : i % 211 === 0 ? "unresolved" : i % 149 === 0 ? "later" : undefined,
  }
})

const FAMILIES = ["Brand", "Surfaces", "Ink", "Edges", "Focus", "Status", "Depth", "Data", "Motion", "Type", "Radius", "Spacing", "Density", "Sidebar"]
const tokens: Token[] = Array.from({ length: 1000 }, (_, i) => {
  const family = FAMILIES[i < 400 ? 0 : i % FAMILIES.length]
  const hue = (i * 37) % 360
  return { name: `--syn-${family.toLowerCase()}-${i + 1}`, family, values: { light: `oklch(0.7 0.12 ${hue})`, dark: `oklch(0.45 0.12 ${hue})` }, reads: i % 13, flags: i % 29 === 0 ? ["unread"] : i % 41 === 0 ? ["literal"] : undefined }
})
const families = FAMILIES.map((name) => ({ name, count: tokens.filter((x) => x.family === name).length }))

const good = (n: number): Step => ({ scenario: `syn.tasks.${n}`, narration: `Step ${n}: a synthetic narration line that explains what a person sees on this screen.` })
const steps: Step[] = Array.from({ length: 40 }, (_, i) => good(i + 2))
steps[5] = { scenario: "syn.tasks.removed", narration: "Points at a scenario that is not in the catalog." }
steps[11] = { scenario: "syn.reports.1", anchor: "no-such-anchor", narration: "Points at an anchor the preview does not have." }
steps[17] = { scenario: "syn.tasks.3", commands: ["bogus-command"], narration: "Runs a command the product does not implement." }
steps[23] = { scenario: scenarios.find((x) => x.status === "later")!.id, narration: "Points at a surface that is marked Later." }

export const syntheticAdapter: StudioAdapter = {
  ...exampleAdapter,
  // The stress Studio declares no properties, so it also measures a Studio exactly as it was before them (AC-53).
  axes: { ...exampleAdapter.axes, inputs: exampleAdapter.axes.inputs.filter((i) => i.section !== "properties") },
  id: "synthetic-stress",
  product: { ...exampleAdapter.product, name: "Stress Studio", revision: "generated" },
  areas,
  scenarios,
  walkthroughs: [{ id: "long-tour", name: "Long tour", goal: "Forty steps, four of them broken on purpose.", illustrative: true, steps }],
  comparisons: [],
  tokens: { source: "generated", columns: ["light", "dark"], families, total: tokens.length, tokens },
}

/** A capture-only Studio: no frame entry, one recorded capture, everything else honestly unavailable. */
const captureSvg = `<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="800"><rect width="1280" height="800" fill="#f4f4f5"/><rect x="40" y="40" width="1200" height="720" rx="16" fill="#fff" stroke="#d4d4d8"/><text x="80" y="120" font-family="sans-serif" font-size="32" fill="#27272a">Illustrative capture</text></svg>`
export const capturesAdapter: StudioAdapter = {
  ...exampleAdapter,
  id: "captures-only",
  frameEntry: undefined,
  target: { ...exampleAdapter.target, fidelity: "static-capture", label: "Static capture" },
  scenarios: exampleAdapter.scenarios.map((x, i) => (i === 0 ? { ...x, captures: { "light:desktop": { src: `data:image/svg+xml;utf8,${encodeURIComponent(captureSvg)}`, w: 1280, h: 800, digest: "illustrative", recordedAt: "Fixed", source: "starter" } } } : x)),
}

/** What "@/adapter" resolves to in an acceptance build (see vite.config.ts): VITE_STUDIO_ADAPTER picks the stress or capture-only adapter. */
export const adapter = import.meta.env.VITE_STUDIO_ADAPTER === "captures" ? capturesAdapter : syntheticAdapter
